# ==============================================================
# SHARED CONFIGURATION (served to ALL microservices by Config Server)
# ==============================================================

# --------------------------------------------------------------
# Database (PostgreSQL)
# --------------------------------------------------------------
# spring.datasource.url=jdbc:postgresql://localhost:5433/smart_sure
spring.datasource.url=jdbc:postgresql://postgres:5432/smart_sure
spring.datasource.username=postgres
spring.datasource.password=612900


# --------------------------------------------------------------
# JPA / Hibernate
# --------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------------------------------------------------------
# Eureka registration
# --------------------------------------------------------------
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=${spring.application.name}
# eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# --------------------------------------------------------------
# JWT secret (shared across all services)
# --------------------------------------------------------------
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# --------------------------------------------------------------
# Redis for caching and storage
# --------------------------------------------------------------
# spring.data.redis.host=localhost
spring.data.redis.host=redis
spring.data.redis.port=6379

# --------------------------------------------------------------
# Logging
# --------------------------------------------------------------
logging.level.root=INFO
# 1. Expose endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
# 2. Prometheus Export
management.metrics.export.prometheus.enabled=true
# 3. Micrometer Tags (VERY IMPORTANT: Allows Grafana to filter per service)
management.metrics.tags.application=${spring.application.name}
# 4. HTTP Request Metrics
management.metrics.enable.http.server.requests=true
management.observations.key-values.http.server.requests.enabled=true
# 5. Distributed Tracing (Zipkin)
# management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

# --------------------------------------------------------------
# Forwarded Headers (so Swagger uses Gateway URL, not direct port)
# --------------------------------------------------------------
server.forward-headers-strategy=framework

# --------------------------------------------------------------
# Swagger / OpenAPI
# --------------------------------------------------------------
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --------------------------------------------------------------
# Razorpay Configuration
# --------------------------------------------------------------
razorpay.key.id=rzp_test_SUGz2hbfTwDAHc
razorpay.key.secret=WtpgwgV4t3I2wTBJ22WWlDbE

# log stash
# Force these services to use Docker names instead of localhost
logging.logstash.server=logstash
spring.rabbitmq.host=rabbitmq

# Fix for CORS (Allows your browser to talk to the API)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*

